// Required plugins (Spring Boot and Java).
plugins {
    id 'org.springframework.boot' version '3.3.10'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.sonarqube' version "6.0.1.5171"
    id 'java'
    id 'jacoco'
}

// Package name.
group = 'br.app.vila'

// Compiler compliance.
java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

// Code analysis.
sonar {
    properties {
        property "sonar.projectKey", System.getenv("SONAR_PROJECT_KEY")
        property "sonar.host.url", System.getenv("SONAR_URL")
        property "sonar.coverage.exclusions", "**/PhonebookApplication**"
    }
}

// Coverage reporting.
jacoco {
    toolVersion = "0.8.12"
}

jacocoTestReport {
    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(false)
    }

    afterEvaluate {
        classDirectories = files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/PhonebookApplication**'])
        })
    }
}

// Dependency repositories.
repositories {
    // Use Maven Central for resolving dependencies.
    maven {
        url "https://repo1.maven.org/maven2"
    }
    mavenCentral()
}

// Dependency list
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.3.10'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.3.10'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.3.10'

    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.3.10'
    testImplementation 'net.minidev:json-smart:2.5.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'org.mockito:mockito-core:5.15.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.15.2'
}

// Test workflow.
test {
    useJUnitPlatform()

    finalizedBy jacocoTestReport
}