services:
  nginx:
    image: nginx:1.29.3
    container_name: frontend
    restart: unless-stopped
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
    volumes:
      - ./etc/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
      - ./etc/.htpasswd:/etc/nginx/conf.d/.htpasswd
    hostname: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - phonebook

  phonebook:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/${APP_NAME}:${BUILD_VERSION}
    container_name: backend
    restart: unless-stopped
    environment:
      - DEBUG_ENABLED=${DEBUG_ENABLED}
      - OBSERVABILITY_ENABLED=${OBSERVABILITY_ENABLED}
      - OBSERVABILITY_LOGS_URL=${OBSERVABILITY_LOGS_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./etc/logback.xml:/home/phonebook/etc/logback.xml
    hostname: backend
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.8.5-ubi
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - mariadb-data:/var/lib/mysql
    hostname: database

volumes:
  mariadb-data: