services:
  frontend:
    image: nginx:1.29.3
    container_name: frontend
    restart: unless-stopped
    environment:
      - BUILD_NAME=${BUILD_NAME}
      - FRONTEND_HOST=${FRONTEND_HOST:-}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN:-}
      - BACKEND_HOST=${BACKEND_HOST:-}
    volumes:
      - ./src/static:/var/www/static
      - ./etc/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
      - ./etc/.htpasswd:/etc/nginx/conf.d/.htpasswd
    hostname: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build: .
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/${BUILD_NAME}:${BUILD_VERSION}
    container_name: backend
    restart: unless-stopped
    environment:
      - BUILD_NAME=${BUILD_NAME}
      - DEBUG_ENABLED=${DEBUG_ENABLED}
      - OBSERVABILITY_ENABLED=${OBSERVABILITY_ENABLED}
      - OBSERVABILITY_LOGS_URL=${OBSERVABILITY_LOGS_URL:-}
      - DB_HOST=${DB_HOST:-}
      - DB_USER=${DB_USER:-}
      - DB_PASS=${DB_PASS:-}
      - DB_NAME=${DB_NAME:-}
    volumes:
      - ./etc/logback.xml:/home/${BUILD_NAME}/etc/logback.xml
    hostname: backend
    depends_on:
      - database

  database:
    image: mongo:8.3.8
    container_name: database
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-}
    volumes:
      - database-data:/data/db
    hostname: database

volumes:
  database-data: