services:
  # Backend definition containing the agent to collect metrics and traces.
  backend:
    build:
      context: ..
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/phonebook:${BUILD_VERSION}