spring.datasource.url=jdbc:mariadb://mariadb:3306/${DB_NAME:phonebook}
spring.datasource.username=${DB_USER:demo}
spring.datasource.password=${DB_PASS:demo}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.main.banner-mode= off