name: Phonebook Pipeline

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".env*"
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "LICENSE"
      - "start.sh"
      - "stop.sh"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: gitea-runner

    steps:
      - name: Download the Project Files
        uses: actions/checkout@v4

      - name: Set Terraform Remote Backend Credentials
        env:
          PROVISIONING_STATE_CREDENTIALS: ${{ secrets.PROVISIONING_STATE_CREDENTIALS }}
        run: mkdir -p ~/.aws/; echo "$PROVISIONING_STATE_CREDENTIALS" > ~/.aws/credentials

      - name: Set the Pipeline Environment
        env:
          BUILD_SETTINGS: ${{ secrets.BUILD_SETTINGS }}
          PROVISIONING_SETTINGS: ${{ secrets.PROVISIONING_SETTINGS }}
        run: echo "$BUILD_SETTINGS" > .env; echo "$PROVISIONING_SETTINGS" > iac/terraform.tfvars

      - name: Compile & Build
        run: ./build.sh

      - name: Test & Coverage
        run: ./test.sh

      - name: Code Analysis
        run: ./codeAnalysis.sh

      - name: Libraries Analysis
        run: ./librariesAnalysis.sh

      - name: Packaging
        run: ./package.sh

      - name: Package Analysis
        run: ./packageAnalysis.sh

      - name: Publishing
        run: ./publish.sh

      - name: Deploy
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          CERTIFICATE_KEY: ${{ secrets.CERTIFICATE }}
        run: ./deploy.sh