name: Phonebook Pipeline

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".env*"
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "LICENSE"
      - "start.sh"
      - "stop.sh"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: gitea-runner

    steps:
      - name: Download the Project Files
        uses: actions/checkout@v4

      - name: Prepare the environment
        env:
          PROVISIONING_STATE_CREDENTIALS: ${{ secrets.PROVISIONING_STATE_CREDENTIALS }}
        run: chmod +x *.sh; mkdir -p ~/.aws/; echo "$PROVISIONING_STATE_CREDENTIALS" > ~/.aws/credentials

      - name: Compile & Build
        env:
          BUILD_DEFINITIONS: ${{ secrets.BUILD_DEFINITIONS }}
        run: ./build.sh

      - name: Test & Coverage
        run: ./test.sh

      - name: Code Analysis
        run: ./codeAnalysis.sh

      - name: Libraries Analysis
        run: ./librariesAnalysis.sh

      - name: Packaging
        run: ./package.sh

      - name: Package Analysis
        run: ./packageAnalysis.sh

      - name: Publishing
        run: ./publish.sh

      - name: Deploy
        env:
          PROVISIONING_DEFINITIONS: ${{ secrets.PROVISIONING_DEFINITIONS }}
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          CERTIFICATE_KEY: ${{ secrets.CERTIFICATE_KEY }}
        run: ./deploy.sh