scrape_configs:
  - job_name: "node"
    scrape_interval: 10s
    static_configs:
      - targets: [ "node-agent:9100" ]

  - job_name: "frontend"
    scrape_interval: 10s
    static_configs:
      - targets: [ "frontend-agent:9101" ]

  - job_name: "backend"
    scrape_interval: 10s
    static_configs:
      - targets: [ "backend:9102" ]

  - job_name: "database"
    scrape_interval: 10s
    static_configs:
      - targets: [ "database-agent:9103" ]
