apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: database
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: DB_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: DB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: DB_ROOT_PASS
          ports:
            - name: tcp
              containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: phonebook
  namespace: backend
spec:
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
        - name: phonebook
          image: ghcr.io/fvilarinho/phonebook:latest
          imagePullPolicy: Always
          env:
            #- name: OBSERVABILITY_ENABLED
            #  value: "true"
            #- name: TRACES_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: phonebook
            #      key: TRACES_HOST
            #- name: METRICS_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: phonebook
            #      key: METRICS_HOST
            #- name: LOGS_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: phonebook
            #      key: LOGS_HOST
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: phonebook
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: phonebook
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: phonebook
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: phonebook
                  key: DB_NAME
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: phonebook-logging-settings
              mountPath: /home/phonebook/etc/logback.xml
              subPath: logback.xml
      volumes:
        - name: phonebook-logging-settings
          configMap:
            name: phonebook-logging-settings
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: BACKEND_HOST
              valueFrom:
                secretKeyRef:
                  name: nginx
                  key: BACKEND_HOST
            #- name: TRACES_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: nginx
            #      key: TRACES_HOST
            #- name: METRICS_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: nginx
            #      key: METRICS_HOST
            #- name: LOGS_HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: nginx
            #      key: LOGS_HOST
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-settings-template
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: nginx-tls-certificate
              mountPath: /etc/tls/certs/fullchain.pem
              subPath: fullchain.pem
            - name: nginx-tls-certificate-key
              mountPath: /etc/tls/private/privkey.pem
              subPath: privkey.pem
            - name: nginx-auth
              mountPath: /etc/nginx/conf.d/.htpasswd
              subPath: .htpasswd
      volumes:
        - name: nginx-settings-template
          configMap:
            name: nginx-settings-template
        - name: nginx-tls-certificate
          configMap:
            name: nginx-tls-certificate
        - name: nginx-tls-certificate-key
          configMap:
            name: nginx-tls-certificate-key
        - name: nginx-auth
          configMap:
            name: nginx-auth