services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${APP_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${APP_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    hostname: grafana
    #ports:
    #  - "3000:3000"  # Expose Grafana UI on port 3000

  fluentd:
    image: ghcr.io/fvilarinho/fluentd:1.0.0
    container_name: fluentd
    restart: always
    volumes:
      - ../etc/fluentd.conf:/opt/bitnami/fluentd/conf/fluentd.conf
    hostname: fluentd
    #ports:
    #  - "9880:9880"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    command:
      - "--query.base-path=/traces"
    hostname: jaeger
    #ports:
    #  - "16686:16686"
    #  - "4317:4317"

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus.yml"
      - '--web.external-url=/metrics'
    volumes:
      - ../etc/prometheus.yml:/etc/prometheus.yml
    hostname: prometheus
    #ports:
    #  - "9090:9090"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: always
    privileged: true
    command:
      - '--path.rootfs=/host'
      - "--web.listen-address=0.0.0.0:9091"
    volumes:
      - '/:/host:ro,delegated'
    hostname: node-exporter
    #ports:
    #  - "9091:9091"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ../etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../etc/.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ../etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ../etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - phonebook
      - prometheus
      - jaeger

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    privileged: true
    command:
      - "--nginx.scrape-uri=http://nginx/stub_status"
      - "--web.listen-address=0.0.0.0:9092"
    hostname: nginx-exporter
    #ports:
    #  - "9092:9092"
    depends_on:
      - nginx

  phonebook:
    build: ..
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/phonebook:${BUILD_VERSION}
    container_name: phonebook
    restart: always
    environment:
      - OTEL_ENABLED=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    hostname: phonebook
    #ports:
    #  - "8080:8080"
    #  - "9093:9893"
    depends_on:
      - mariadb
      - jaeger
      - fluentd

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    hostname: mariadb
    #ports:
    #  - "3306:3306"

  mariadb-exporter:
    image: quay.io/prometheus/mysqld-exporter:latest
    container_name: mariadb-exporter
    restart: always
    environment:
      - DB_ROOT_PASS=${DB_ROOT_PASS}
    command:
      - "--mysqld.username=root:$DB_ROOT_PASS"
      - "--mysqld.address=mariadb:3306"
      - "--web.listen-address=0.0.0.0:9094"
    hostname: mariadb-exporter
    #ports:
    #  - "9094:9094"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  grafana_data: