name: Phonebook Pipeline

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".*.template"
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "LICENSE"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    env:
      BUILD_DEFINITIONS: ${{ secrets.BUILD_DEFINITIONS }}
    runs-on: ubuntu-latest

    steps:
      - name: Download the Project Files
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Prepare the Environment
        run: chmod +x *.sh; chmod +x ./bin/*.sh; npm install snyk -g

      - name: Compile & Build
        run: ./build.sh

      - name: Test & Coverage
        run: ./test.sh

      - name: Code Analysis
        run: ./codeAnalysis.sh

      - name: Libraries Analysis
        run: ./librariesAnalysis.sh

      - name: Packaging
        run: ./package.sh

      - name: Package Analysis
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL}}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID}}
        run: ./packageAnalysis.sh

      - name: Publishing
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL}}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID}}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRT_PASSWORD}}
        run: ./publish.sh

      - name: Notify
        if: always()
        run: ./notify.sh "${{ job.status }}"