name: Phonebook Pipeline

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".*.template"
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "LICENSE"

permissions:
  contents: read

jobs:
  build:
    name: Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Download the Project Files
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Snyk
        run: npm install --ignore-scripts -g snyk@1.1307.0

      - name: Compile & Build
        run: ./build.sh

      - name: Test & Coverage
        run: ./test.sh

      - name: Code Analysis
        env:
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./codeAnalysis.sh

      - name: Libraries Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: ./librariesAnalysis.sh

      - name: Packaging
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
        run: ./package.sh

      - name: Package Analysis
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN}}
        run: ./packageAnalysis.sh

      - name: Publishing
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh

      - name: Notify
        if: always()
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: ./notify.sh "${{ job.status }}"